export const AppInfo = {
  baseUrlAPI: 'https://api.joolkart.com', // Dev Server
  // baseUrlAPI: 'https://dev-api.joolkart.com', // Dev Server
  // baseUrlAPI: 'http://uat-api.joolkart.com', //UAT server
  // baseUrlAPI: 'https://uatnew-api.joolkart.com', //New UAT server
  // baseUrlAPI: 'https://api.joolkart.com', //Production server
  apiVersion: 'v1',
  serviceTimeOut: 20000,
};
export const apis = {
  getRequest: 'GET',
  postRequest: 'POST',
  deleteRequest: 'DELETE',
  putRequest: 'PUT',
  baseURL: AppInfo.baseUrlAPI + '/' + AppInfo.apiVersion + '/',
  dummy_api: '/web/getTnC',
  home: 'home',
  category: 'category',
  login: 'login',
  register: 'register',
  contact: 'contact',
  user: 'user',
  about: 'page/about',
  updateProfile: 'profile-update',
  otp: 'otp',
  sendotp: 'send-otp',
  verifyotp: 'verify-otp',
  addressShipping: 'address',
  privacyPolicy: 'page/privacy-policy',
  termCondition: 'page/terms-condition',
  fnq: 'page/fnq',
  check_member: 'check-member',
  feedback: 'feedback',
  verifyotp2: 'verifyotp',
  changepassword: 'change-password',
  logout: 'logout',
  productDetail: 'product-detail/',
  wishlist: 'wishlist',
  recentview: 'recent-view',
  addressDefault: 'address-default',
  notification: 'notification',
  review: 'review',
  cart: 'cart',
  productFilter: 'product-filter',
  state: 'state',
  completeOrder: 'complete-order',
  orderlist: 'order-list',
  orderInvoice: 'order-invoice',
  cancelOrder: 'change/status/',
  productSearch: 'product-search/',
  recentsearch: "recent-search/",
  socialLogin: "social-login",
  onSaveToken: "customer-notification-register",
  onSaveTokenMap: "customer-notification-map",
  onSaveTokenUnMap: "customer-notification-unmap",
  sellerProducts: "product-by-seller",
  searchSuggesion: "product-search-without-limit",
  changeStatus: "change/order/status",
  referral: "referral",
  referralCode: "refer-code",
  returnResaon: "reasons",
  coupons: "coupons",
  applyCoupon: "apply-coupon",
  applyJoolcoin: "apply-joolcoin",
  sendOtpEmail: "send-otp-email",
  verifyOtpEmail: "verify-otp-email",
  storeReferralUrl: "store-refer-url",
  check_pincode: "check-pincode",
  customer_notification: "customer-notification",
  serviceability: "check-serviceability",
  customerAllNotification: "customerAllNotification",
  notificatinStatus: "notification-status",
  serviceabilityLoginUser: "check-serviceability-login-user",
};